# Generated by Django 6.1 on 2026-09-04 01:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('people', '0004_review_governance_wave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContemplativeContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('breath_awareness', 'BREATH_AWARENESS'), ('mindful_walk', 'MINDFUL_WALK'), ('gratitude', 'GRATITUDE'), ('values_reflection', 'VALUES_REFLECTION'), ('loving_kindness', 'LOVING_KINDNESS'), ('meditation', 'MEDITATION')], default='mindful_walk', max_length=50)),
                ('tradition', models.CharField(choices=[('secular', 'SECULAR'), ('interfaith', 'INTERFAITH'), ('buddhist', 'BUDDHIST'), ('christian', 'CHRISTIAN'), ('indigenous', 'INDIGENOUS'), ('afro_brazilian', 'AFRO_BRAZILIAN'), ('spiritist', 'SPIRITIST'), ('other', 'OTHER')], db_index=True, default='secular', max_length=50)),
                ('content_text', models.TextField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_secular_equivalent', models.BooleanField(default=True)),
                ('author_attribution', models.CharField(max_length=255)),
                ('editorial_review_status', models.CharField(choices=[('draft', 'DRAFT'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], db_index=True, default='approved', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('diversity_and_safety_cleared', models.BooleanField(default=True)),
                ('non_coercive_language_verified', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contemplative_contents', to='clinics.clinic')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contemplative_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_network_contemplative_contents',
            },
        ),
        migrations.CreateModel(
            name='ContemplativeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('duration_spent_seconds', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contemplative_histories', to='clinics.clinic')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='support_network.contemplativecontent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contemplative_histories', to='people.patientprofile')),
            ],
            options={
                'db_table': 'support_network_contemplative_histories',
            },
        ),
        migrations.CreateModel(
            name='LegalGuardianConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_phone', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('document_hash', models.CharField(max_length=128)),
                ('verification_status', models.CharField(choices=[('pending', 'PENDING'), ('verified', 'VERIFIED'), ('rejected', 'REJECTED'), ('revoked', 'REVOKED'), ('disputed', 'DISPUTED')], db_index=True, default='pending', max_length=30)),
                ('verification_method', models.CharField(default='ASSISTED_OPERATION', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_consents', to='clinics.clinic')),
                ('guardian_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarded_patients', to=settings.AUTH_USER_MODEL)),
                ('minor_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_consents', to='people.patientprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_guardian_consents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guardian_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_network_guardian_consents',
            },
        ),
        migrations.CreateModel(
            name='MinorPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.CharField(db_index=True, default='BR', max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('child_max_age', models.PositiveSmallIntegerField(default=11)),
                ('young_teen_max_age', models.PositiveSmallIntegerField(default=15)),
                ('older_teen_max_age', models.PositiveSmallIntegerField(default=17)),
                ('requires_guardian_consent_under', models.PositiveSmallIntegerField(default=16)),
                ('assent_required_from', models.PositiveSmallIntegerField(default=12)),
                ('directory_search_allowed_under_18', models.BooleanField(default=False)),
                ('open_messaging_allowed_under_18', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'support_network_minor_policy_versions',
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'version'), name='unique_jurisdiction_policy_version')],
            },
        ),
        migrations.CreateModel(
            name='MinorProfileGuardrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_tier', models.CharField(choices=[('child', 'CHILD'), ('young_teen', 'YOUNG_TEEN'), ('older_teen', 'OLDER_TEEN'), ('adult', 'ADULT')], db_index=True, default='adult', max_length=20)),
                ('is_minor', models.BooleanField(db_index=True, default=False)),
                ('is_emancipated', models.BooleanField(default=False)),
                ('guardian_consent_verified', models.BooleanField(db_index=True, default=False)),
                ('directory_search_allowed', models.BooleanField(default=False)),
                ('open_messaging_allowed', models.BooleanField(default=False)),
                ('export_requires_guardian_approval', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_guardrails', to='clinics.clinic')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minor_guardrail', to='people.patientprofile')),
            ],
            options={
                'db_table': 'support_network_minor_guardrails',
            },
        ),
        migrations.CreateModel(
            name='SpiritualityPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('tradition', models.CharField(choices=[('secular', 'SECULAR'), ('interfaith', 'INTERFAITH'), ('buddhist', 'BUDDHIST'), ('christian', 'CHRISTIAN'), ('indigenous', 'INDIGENOUS'), ('afro_brazilian', 'AFRO_BRAZILIAN'), ('spiritist', 'SPIRITIST'), ('other', 'OTHER')], default='secular', max_length=50)),
                ('secular_alternative_enabled', models.BooleanField(default=True)),
                ('opt_in_date', models.DateTimeField(blank=True, null=True)),
                ('disclaimer_acknowledged', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirituality_preferences', to='clinics.clinic')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spirituality_preference', to='people.patientprofile')),
            ],
            options={
                'db_table': 'support_network_spirituality_preferences',
            },
        ),
        migrations.CreateModel(
            name='SupportNetworkAuditMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('invitations_sent', models.PositiveIntegerField(default=0)),
                ('invitations_accepted', models.PositiveIntegerField(default=0)),
                ('invitations_revoked', models.PositiveIntegerField(default=0)),
                ('relationships_revoked', models.PositiveIntegerField(default=0)),
                ('authorization_failures', models.PositiveIntegerField(default=0)),
                ('average_latency_ms', models.FloatField(default=0.0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_audit_metrics', to='clinics.clinic')),
            ],
            options={
                'db_table': 'support_network_audit_metrics',
            },
        ),
        migrations.CreateModel(
            name='SupportNetworkInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invitee_phone', models.CharField(blank=True, max_length=50)),
                ('relationship_type', models.CharField(choices=[('family', 'FAMILY'), ('friend', 'FRIEND'), ('legal_guardian', 'LEGAL_GUARDIAN'), ('peer', 'PEER'), ('other', 'OTHER')], default='friend', max_length=50)),
                ('invitation_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED'), ('expired', 'EXPIRED'), ('revoked', 'REVOKED')], db_index=True, default='pending', max_length=30)),
                ('permissions_offered', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_invitations', to='clinics.clinic')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_invitations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_invitations', to='people.patientprofile')),
            ],
            options={
                'db_table': 'support_network_invitations',
            },
        ),
        migrations.CreateModel(
            name='SupportNetworkRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporter_name', models.CharField(max_length=255)),
                ('supporter_email', models.EmailField(max_length=254)),
                ('supporter_phone', models.CharField(blank=True, max_length=50)),
                ('relationship_type', models.CharField(choices=[('family', 'FAMILY'), ('friend', 'FRIEND'), ('legal_guardian', 'LEGAL_GUARDIAN'), ('peer', 'PEER'), ('other', 'OTHER')], default='friend', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('established_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_relationships', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_relationships', to='people.patientprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_support_relationships', to=settings.AUTH_USER_MODEL)),
                ('supporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_network_relationships',
            },
        ),
        migrations.CreateModel(
            name='SupportNetworkPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_scope', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_permissions', to='clinics.clinic')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_support_permissions', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='support_network.supportnetworkrelationship')),
            ],
            options={
                'db_table': 'support_network_permissions',
            },
        ),
        migrations.CreateModel(
            name='SupportNetworkRolloutFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('min_age_tier', models.CharField(choices=[('child', 'CHILD'), ('young_teen', 'YOUNG_TEEN'), ('older_teen', 'OLDER_TEEN'), ('adult', 'ADULT')], default='child', max_length=20)),
                ('cohort_name', models.CharField(default='GENERAL', max_length=50)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_rollout_flags', to='clinics.clinic')),
            ],
            options={
                'db_table': 'support_network_rollout_flags',
            },
        ),
        migrations.CreateModel(
            name='UrgentActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id', models.UUIDField(default=uuid.uuid4)),
                ('action_type', models.CharField(max_length=50)),
                ('confirmed_explicitly', models.BooleanField(default=False)),
                ('disclaimer_shown', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_action_logs', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_action_logs', to='people.patientprofile')),
            ],
            options={
                'db_table': 'support_network_urgent_action_logs',
            },
        ),
        migrations.CreateModel(
            name='UrgentLocalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(db_index=True, default='BR', max_length=50)),
                ('resource_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('hours_of_operation', models.CharField(default='24 horas', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_urgent_resources', to='clinics.clinic')),
            ],
            options={
                'db_table': 'support_network_urgent_resources',
            },
        ),
        migrations.CreateModel(
            name='UrgentSupportPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_instructions', models.TextField(blank=True)),
                ('calming_strategies', models.JSONField(default=list)),
                ('preferred_language', models.CharField(default='pt-BR', max_length=10)),
                ('region', models.CharField(default='BR', max_length=50)),
                ('last_reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_period_days', models.PositiveIntegerField(default=90)),
                ('disclaimer_acknowledged', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_support_plans', to='clinics.clinic')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_support_plan', to='people.patientprofile')),
            ],
            options={
                'db_table': 'support_network_urgent_plans',
            },
        ),
        migrations.CreateModel(
            name='UrgentSupportContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('message_template', models.TextField(blank=True, default='Olá, estou em um momento difícil e gostaria de conversar ou de sua presença, quando puder.')),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_support_contacts', to='clinics.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='support_network.urgentsupportplan')),
            ],
            options={
                'db_table': 'support_network_urgent_contacts',
                'ordering': ['priority_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contemplativecontent',
            index=models.Index(fields=['tradition', 'is_active', 'editorial_review_status'], name='support_net_traditi_e0db57_idx'),
        ),
        migrations.AddIndex(
            model_name='contemplativehistory',
            index=models.Index(fields=['clinic', 'patient', 'accessed_at'], name='support_net_clinic__552d94_idx'),
        ),
        migrations.AddIndex(
            model_name='legalguardianconsent',
            index=models.Index(fields=['clinic', 'minor_patient', 'verification_status'], name='support_net_clinic__3c05f1_idx'),
        ),
        migrations.AddIndex(
            model_name='legalguardianconsent',
            index=models.Index(fields=['guardian_email', 'verification_status'], name='support_net_guardia_da6194_idx'),
        ),
        migrations.AddIndex(
            model_name='minorprofileguardrail',
            index=models.Index(fields=['clinic', 'is_minor', 'guardian_consent_verified'], name='support_net_clinic__c04447_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportnetworkauditmetric',
            constraint=models.UniqueConstraint(fields=('clinic', 'metric_date'), name='unique_clinic_metric_date'),
        ),
        migrations.AddIndex(
            model_name='supportnetworkinvitation',
            index=models.Index(fields=['clinic', 'patient', 'status'], name='support_net_clinic__6226a2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnetworkinvitation',
            index=models.Index(fields=['invitee_email', 'status'], name='support_net_invitee_f30a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnetworkrelationship',
            index=models.Index(fields=['clinic', 'patient', 'is_active'], name='support_net_clinic__5b419b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnetworkrelationship',
            index=models.Index(fields=['supporter_email', 'is_active'], name='support_net_support_64fbc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportnetworkrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('clinic', 'patient', 'supporter_email'), name='unique_active_support_relationship'),
        ),
        migrations.AddIndex(
            model_name='supportnetworkpermission',
            index=models.Index(fields=['clinic', 'permission_scope', 'is_active'], name='support_net_clinic__588b54_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportnetworkpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('relationship', 'permission_scope'), name='unique_active_support_permission'),
        ),
        migrations.AddConstraint(
            model_name='supportnetworkrolloutflag',
            constraint=models.UniqueConstraint(fields=('clinic', 'feature_name', 'cohort_name'), name='unique_clinic_feature_cohort'),
        ),
        migrations.AddIndex(
            model_name='urgentactionlog',
            index=models.Index(fields=['clinic', 'patient', 'triggered_at'], name='support_net_clinic__a5c6a3_idx'),
        ),
    ]
