# Generated by Django 6.1 on 2026-09-02 12:29

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0014_clinicmembership_authorized_by_and_more"),
        ("people", "0003_carerelationship_authorized_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "Muito mal"),
                            (2, "Mal"),
                            (3, "Neutro"),
                            (4, "Bem"),
                            (5, "Muito bem"),
                        ]
                    ),
                ),
                ("emotions", models.JSONField(blank=True, default=list)),
                (
                    "intensity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("context", models.TextField(max_length=4000)),
                ("triggers", models.TextField(blank=True, max_length=2000)),
                ("reactions", models.TextField(blank=True, max_length=2000)),
                ("strategies", models.TextField(blank=True, max_length=2000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("shareable", "Verde"),
                            ("confirmation_required", "Amarelo"),
                            ("private", "Vermelho"),
                        ],
                        default="private",
                        max_length=24,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="people.patientprofile",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["clinic", "patient_profile", "created_at"],
                        name="journal_patient_created_idx",
                    ),
                    models.Index(
                        fields=["clinic", "visibility"],
                        name="journal_clinic_visibility_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
