# Generated by Django 6.1 on 2026-09-02 13:40

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('journal', '0002_journalaccessrequest'),
        ('people', '0003_carerelationship_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Check-in Diário', max_length=255)),
                ('version', models.CharField(default='v1.0', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.JSONField(default=list)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_questionnaires', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_version', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('period', models.CharField(default='daily', max_length=16)),
                ('answers', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('shareable', 'Verde'), ('confirmation_required', 'Amarelo'), ('private', 'Vermelho')], default='private', max_length=24)),
                ('is_draft', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('previous_version_answers', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='people.patientprofile')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin_responses', to='journal.checkinquestionnaire')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='checkinquestionnaire',
            constraint=models.UniqueConstraint(fields=('clinic', 'version'), name='unique_checkin_questionnaire_version_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['clinic', 'patient_profile', 'date'], name='checkin_patient_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('clinic', 'patient_profile', 'date', 'period'), name='unique_patient_checkin_per_date_period'),
        ),
    ]
