# Generated by Django 6.1 on 2026-09-02 13:57

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('journal', '0003_checkinquestionnaire_dailycheckin_and_more'),
        ('people', '0003_carerelationship_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSignalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('question_key', models.CharField(max_length=64)),
                ('operator', models.CharField(choices=[('gte', 'Maior ou igual a'), ('less_or_equal', 'Menor ou igual a'), ('equal', 'Igual a')], max_length=24)),
                ('threshold', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('monitoring_window', models.CharField(choices=[('business_hours', 'Horário comercial'), ('extended', 'Horário estendido')], default='business_hours', max_length=24)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_signal_rules_authorized', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_signal_rules', to='clinics.clinic')),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='clinical_signal_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HumanTriageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_review', 'Em revisão'), ('closed', 'Encerrado')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_decision', models.CharField(blank=True, max_length=255)),
                ('is_emergency', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_items', to='journal.dailycheckin')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_triage_items', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_triage_items', to='people.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_triage_items', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_items', to='journal.clinicalsignalrule')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='clinicalsignalrule',
            index=models.Index(fields=['clinic', 'question_key', 'is_active'], name='signal_rule_clinic_key_idx'),
        ),
        migrations.AddIndex(
            model_name='humantriageitem',
            index=models.Index(fields=['clinic', 'status', 'created_at'], name='triage_clinic_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='humantriageitem',
            constraint=models.UniqueConstraint(fields=('checkin', 'rule'), name='unique_triage_item_per_checkin_rule'),
        ),
    ]
