# Generated by Django 6.1 on 2026-09-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_clinicalsignalrule_humantriageitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humantriageitem',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_items', to='journal.dailycheckin'),
        ),
    ]
