# Generated by Django 6.1 on 2026-09-02 16:50

import scheduling.messaging_models
import scheduling.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(max_length=255, storage=scheduling.storage.PrivateAttachmentStorage(), upload_to=scheduling.messaging_models.message_attachment_upload_to),
        ),
    ]
