# Generated by Django 6.1 on 2026-09-02 18:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('people', '0003_carerelationship_authorized_by_and_more'),
        ('scheduling', '0002_alter_messageattachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_period', models.CharField(blank=True, max_length=32)),
                ('contact_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('offered', 'Vaga oferecida'), ('filled', 'Encaixado'), ('canceled', 'Cancelado')], default='waiting', max_length=16)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clinics.clinic')),
                ('filled_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_fill', to='scheduling.appointment')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='people.patientprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries_requested', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='scheduling.service')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='scheduling.unit')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status', 'created_at'], name='waitlist_clinic_status_idx'), models.Index(fields=['clinic', 'unit', 'status'], name='waitlist_clinic_unit_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
