# Generated by Django 6.1 on 2026-09-04 01:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('hydration', 'HYDRATION'), ('breathing', 'BREATHING'), ('reflection', 'REFLECTION'), ('routine', 'ROUTINE')], default='reflection', max_length=30)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('daily_cap', models.PositiveIntegerField(default=1)),
                ('supportive_message', models.TextField(default='Cada passo no seu tempo é valioso. Pausas fazem parte do caminho.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'communities_gamification_milestone',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('group_type', models.CharField(choices=[('private_invite_only', 'PRIVATE_INVITE_ONLY'), ('institutional', 'INSTITUTIONAL'), ('thematic_approved', 'THEMATIC_APPROVED')], default='thematic_approved', max_length=30)),
                ('visibility', models.CharField(choices=[('private', 'PRIVATE'), ('tenant_directory', 'TENANT_DIRECTORY'), ('hidden', 'HIDDEN')], default='tenant_directory', max_length=30)),
                ('rules_text', models.TextField(default='Espaço de convivência respeitosa, sigilo mútuo e acolhimento.')),
                ('rules_version', models.PositiveIntegerField(default=1)),
                ('allowed_age_tiers', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('slow_mode_seconds', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_groups', to='clinics.clinic')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_community_groups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_community_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('role_offered', models.CharField(choices=[('owner', 'OWNER'), ('moderator', 'MODERATOR'), ('member', 'MEMBER')], default='member', max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED'), ('expired', 'EXPIRED'), ('revoked', 'REVOKED')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_invitations', to='clinics.clinic')),
                ('community_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='communities.communitygroup')),
                ('invitee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_community_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_community_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_invitation',
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'OWNER'), ('moderator', 'MODERATOR'), ('member', 'MEMBER')], default='member', max_length=20)),
                ('pseudonym', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('muted', 'MUTED'), ('suspended', 'SUSPENDED'), ('left', 'LEFT'), ('removed', 'REMOVED')], default='active', max_length=20)),
                ('rules_accepted_version', models.PositiveIntegerField(default=1)),
                ('rules_accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to='clinics.clinic')),
                ('community_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.communitygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_membership',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('sanitized_content', models.TextField()),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('edited', 'EDITED'), ('hidden_by_moderator', 'HIDDEN_BY_MODERATOR'), ('deleted', 'DELETED')], default='published', max_length=30)),
                ('is_pinned', models.BooleanField(default=False)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='clinics.clinic')),
                ('community_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.communitygroup')),
            ],
            options={
                'db_table': 'communities_post',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('sanitized_content', models.TextField()),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('edited', 'EDITED'), ('hidden_by_moderator', 'HIDDEN_BY_MODERATOR'), ('deleted', 'DELETED')], default='published', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='clinics.clinic')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communities.communitycomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.communitypost')),
            ],
            options={
                'db_table': 'communities_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('is_clean', models.BooleanField(default=True)),
                ('scan_status', models.CharField(default='CLEAN', max_length=30)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_attachments', to='clinics.clinic')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communities.communitypost')),
            ],
            options={
                'db_table': 'communities_attachment',
            },
        ),
        migrations.CreateModel(
            name='CommunityReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('support', 'SUPPORT'), ('heart', 'HEART'), ('helpful', 'HELPFUL'), ('thank_you', 'THANK_YOU')], default='support', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='clinics.clinic')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='communities.communitycomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='communities.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_reaction',
            },
        ),
        migrations.CreateModel(
            name='CommunityRolloutFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communities_enabled', models.BooleanField(default=False)),
                ('gamification_enabled', models.BooleanField(default=False)),
                ('allowed_age_tiers', models.JSONField(default=list)),
                ('moderation_kill_switch', models.BooleanField(default=False)),
                ('slow_mode_enforced', models.BooleanField(default=False)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_rollout_flag', to='clinics.clinic')),
            ],
            options={
                'db_table': 'communities_rollout_flag',
            },
        ),
        migrations.CreateModel(
            name='GamificationProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_date', models.DateField()),
                ('count_today', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_progress_records', to='clinics.clinic')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='communities.gamificationmilestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_gamification_progress',
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField(db_index=True)),
                ('violation_category', models.CharField(choices=[('harassment', 'HARASSMENT'), ('hate_speech', 'HATE_SPEECH'), ('unsafe_content', 'UNSAFE_CONTENT'), ('spam', 'SPAM'), ('privacy_violation', 'PRIVACY_VIOLATION'), ('other', 'OTHER')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('critical', 'CRITICAL')], default='medium', max_length=20)),
                ('priority_score', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('pending_triage', 'PENDING_TRIAGE'), ('in_review', 'IN_REVIEW'), ('actioned', 'ACTIONED'), ('dismissed', 'DISMISSED'), ('appealed', 'APPEALED'), ('resolved', 'RESOLVED')], default='pending_triage', max_length=30)),
                ('decision', models.CharField(blank=True, choices=[('no_action', 'NO_ACTION'), ('content_removed', 'CONTENT_REMOVED'), ('user_warned', 'USER_WARNED'), ('user_suspended', 'USER_SUSPENDED'), ('user_banned', 'USER_BANNED')], max_length=30, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField()),
                ('sla_breached', models.BooleanField(default=False)),
                ('requires_double_review', models.BooleanField(default=False)),
                ('second_decision', models.CharField(blank=True, choices=[('no_action', 'NO_ACTION'), ('content_removed', 'CONTENT_REMOVED'), ('user_warned', 'USER_WARNED'), ('user_suspended', 'USER_SUSPENDED'), ('user_banned', 'USER_BANNED')], max_length=30, null=True)),
                ('second_justification', models.TextField(blank=True, default='')),
                ('second_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases', to='clinics.clinic')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('second_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_reviewed_moderation_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_moderation_case',
                'ordering': ['-priority_score', 'sla_deadline'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_name', models.CharField(max_length=100)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_audit_records', to='clinics.clinic')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='communities.moderationcase')),
            ],
            options={
                'db_table': 'communities_moderation_audit',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal_grounds', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=20)),
                ('reviewer_decision', models.CharField(blank=True, default='', max_length=30)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_moderation_appeals', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_appeals', to='clinics.clinic')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_moderation_appeals', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='communities.moderationcase')),
            ],
            options={
                'db_table': 'communities_moderation_appeal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_snapshot', models.TextField()),
                ('author_id', models.UUIDField()),
                ('metadata_json', models.JSONField(default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='clinics.clinic')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='communities.moderationcase')),
            ],
            options={
                'db_table': 'communities_evidence_vault',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleGamificationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_opted_in', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('reminders_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('max_daily_reminders', models.PositiveIntegerField(default=3)),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profiles', to='clinics.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_gamification_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSocialBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_blocked_users', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_blocks', to='clinics.clinic')),
            ],
            options={
                'db_table': 'communities_user_block',
            },
        ),
        migrations.CreateModel(
            name='UserSocialMute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_mutes', to='clinics.clinic')),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_muted_by', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_muted_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_user_mute',
            },
        ),
        migrations.CreateModel(
            name='CommunityAuditMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField()),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('comments_created', models.PositiveIntegerField(default=0)),
                ('reports_submitted', models.PositiveIntegerField(default=0)),
                ('moderation_actions_taken', models.PositiveIntegerField(default=0)),
                ('appeals_submitted', models.PositiveIntegerField(default=0)),
                ('appeals_upheld', models.PositiveIntegerField(default=0)),
                ('average_sla_resolution_minutes', models.FloatField(default=0.0)),
                ('rate_limit_hits', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_metrics', to='clinics.clinic')),
            ],
            options={
                'db_table': 'communities_audit_metric',
                'indexes': [models.Index(fields=['clinic', 'metric_date'], name='communities_clinic__ce5fe6_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'metric_date'), name='unique_community_metric_per_clinic_day')],
            },
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['clinic', 'is_active', 'visibility'], name='communities_clinic__c64200_idx'),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['clinic', 'group_type'], name='communities_clinic__300a7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitygroup',
            constraint=models.UniqueConstraint(fields=('clinic', 'slug'), name='unique_community_group_slug_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['clinic', 'invitee_email', 'status'], name='communities_clinic__d7a96e_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['token_hash', 'status'], name='communities_token_h_e493dc_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['clinic', 'user', 'status'], name='communities_clinic__ca8622_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community_group', 'status', 'role'], name='communities_communi_a237fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitymembership',
            constraint=models.UniqueConstraint(fields=('community_group', 'user'), name='unique_community_membership_per_group'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['clinic', 'community_group', 'status', '-created_at'], name='communities_clinic__8b55ac_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['clinic', 'author', 'status'], name='communities_clinic__c5fa08_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['clinic', 'post', 'status', 'created_at'], name='communities_clinic__ad06b7_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['clinic', 'author'], name='communities_clinic__e0aa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='communityattachment',
            index=models.Index(fields=['clinic', 'post'], name='communities_clinic__b5c923_idx'),
        ),
        migrations.AddIndex(
            model_name='communityattachment',
            index=models.Index(fields=['sha256_hash'], name='communities_sha256__ed8692_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreaction',
            index=models.Index(fields=['clinic', 'post', 'reaction_type'], name='communities_clinic__df57e6_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreaction',
            index=models.Index(fields=['clinic', 'comment', 'reaction_type'], name='communities_clinic__90a11c_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'user'), name='unique_post_reaction_per_user'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('comment', 'user'), name='unique_comment_reaction_per_user'),
        ),
        migrations.AddIndex(
            model_name='gamificationprogress',
            index=models.Index(fields=['clinic', 'user', 'occurred_date'], name='communities_clinic__d9ca0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamificationprogress',
            constraint=models.UniqueConstraint(fields=('clinic', 'user', 'milestone', 'occurred_date'), name='unique_gamification_progress_per_day'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['clinic', 'status', '-priority_score'], name='communities_clinic__b192b8_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['clinic', 'assigned_moderator', 'status'], name='communities_clinic__ce68dc_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['clinic', 'target_type', 'target_id'], name='communities_clinic__f74747_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaudittrail',
            index=models.Index(fields=['clinic', 'case', 'created_at'], name='communities_clinic__ffbd19_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationappeal',
            index=models.Index(fields=['clinic', 'status'], name='communities_clinic__cc76f5_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationappeal',
            index=models.Index(fields=['case', 'appellant'], name='communities_case_id_3e6bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencevault',
            index=models.Index(fields=['clinic', 'case'], name='communities_clinic__e5417c_idx'),
        ),
        migrations.AddIndex(
            model_name='responsiblegamificationprofile',
            index=models.Index(fields=['clinic', 'user', 'is_opted_in'], name='communities_clinic__1cf478_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialblock',
            index=models.Index(fields=['clinic', 'blocker'], name='communities_clinic__af2b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialblock',
            index=models.Index(fields=['clinic', 'blocked_user'], name='communities_clinic__d357de_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersocialblock',
            constraint=models.UniqueConstraint(fields=('clinic', 'blocker', 'blocked_user'), name='unique_social_block_per_pair'),
        ),
        migrations.AddIndex(
            model_name='usersocialmute',
            index=models.Index(fields=['clinic', 'muter'], name='communities_clinic__5969b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersocialmute',
            constraint=models.UniqueConstraint(fields=('clinic', 'muter', 'muted_user'), name='unique_social_mute_per_pair'),
        ),
    ]
