# Generated by Django 6.1 on 2026-09-04 00:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('people', '0004_review_governance_wave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('clinical_rationale', models.TextField()),
                ('contraindications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_signature', 'Aguardando assinatura profissional'), ('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('revoked', 'Revogado')], default='draft', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_digest', models.CharField(blank=True, max_length=64)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='people.patientprofile')),
                ('prescribing_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_care_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_description', models.CharField(max_length=255)),
                ('target_frequency', models.CharField(default='daily', max_length=64)),
                ('guidance', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='routines.careplan')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_actions', to='clinics.clinic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanPatientResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version_reviewed', models.IntegerField()),
                ('decision', models.CharField(choices=[('accepted', 'Aceito'), ('refused', 'Recusado'), ('paused', 'Pausado pelo paciente'), ('review_requested', 'Revisão solicitada')], max_length=32)),
                ('patient_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_responses', to='routines.careplan')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_patient_responses', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diária'), ('weekdays', 'Dias úteis'), ('specific_days', 'Dias específicos'), ('flexible', 'Meta flexível')], default='daily', max_length=32)),
                ('active_days', models.JSONField(blank=True, default=list)),
                ('target_count', models.IntegerField(default=1)),
                ('time_window', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('night', 'Madrugada'), ('any_time', 'A qualquer momento'), ('exact_time', 'Horário fixo')], default='any_time', max_length=32)),
                ('target_time', models.TimeField(blank=True, null=True)),
                ('target_duration_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('archived', 'Arquivado')], default='active', max_length=32)),
                ('paused_until', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_lead_minutes', models.IntegerField(default=15)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone_name', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='people.patientprofile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('plan_key', models.CharField(db_index=True, max_length=128)),
                ('version', models.IntegerField(default=1)),
                ('is_canceled', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_occurrences', to='clinics.clinic')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='routines.habit')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='HabitCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completed', 'Concluído'), ('partial', 'Parcial'), ('postponed', 'Adiado'), ('skipped', 'Ignorado')], default='completed', max_length=32)),
                ('intensity_level', models.IntegerField(blank=True, null=True)),
                ('duration_minutes_executed', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history', models.JSONField(blank=True, default=list)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_checkins', to='clinics.clinic')),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='routines.habitoccurrence')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationConsentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_consent_shares', to='clinics.clinic')),
                ('granted_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_medication_shares', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_consent_shares', to='people.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=255)),
                ('presentation', models.CharField(max_length=128)),
                ('prescribed_dose', models.CharField(max_length=128)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('sublingual', 'Sublingual'), ('topical', 'Tópico'), ('inhalation', 'Inalação'), ('injectable', 'Injetável'), ('ophthalmic', 'Oftálmico'), ('nasal', 'Nasal'), ('other', 'Outro')], default='oral', max_length=32)),
                ('schedule_times', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_continuous', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('prescriber_name', models.CharField(max_length=255)),
                ('prescriber_registration', models.CharField(max_length=64)),
                ('prescription_date', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='people.patientprofile')),
            ],
            options={
                'ordering': ['-start_date', 'medication_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('taken', 'Tomado'), ('late', 'Tomado com atraso'), ('omitted', 'Omitido'), ('not_reported', 'Não informado')], default='not_reported', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='clinics.clinic')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='routines.prescribedmedication')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='RoutineBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('time_window', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('night', 'Madrugada'), ('any_time', 'A qualquer momento'), ('exact_time', 'Horário fixo')], default='morning', max_length=32)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_blocks', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_blocks', to='people.patientprofile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='habit',
            name='routine_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='routines.routineblock'),
        ),
        migrations.CreateModel(
            name='SleepDeviceSyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='apple_health', max_length=64)),
                ('external_record_id', models.CharField(max_length=255)),
                ('sync_cursor', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_revoked', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_device_sync_records', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_device_sync_records', to='people.patientprofile')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_date', models.DateField(db_index=True)),
                ('bedtime', models.DateTimeField()),
                ('sleep_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('wake_time', models.DateTimeField()),
                ('out_of_bed_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('perceived_quality', models.IntegerField(default=3)),
                ('nap_duration_minutes', models.IntegerField(default=0)),
                ('provenance', models.CharField(choices=[('self_reported', 'Autorrelato'), ('device_imported', 'Importado de dispositivo'), ('clinical_estimate', 'Estimativa descritiva')], default='self_reported', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('external_record_id', models.CharField(blank=True, max_length=255)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to='people.patientprofile')),
            ],
            options={
                'ordering': ['-reference_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='habitoccurrence',
            constraint=models.UniqueConstraint(fields=('habit', 'scheduled_date'), name='unique_habit_occurrence_per_date'),
        ),
        migrations.AddConstraint(
            model_name='medicationconsentshare',
            constraint=models.UniqueConstraint(fields=('patient_profile', 'granted_to_user'), name='unique_medication_share_per_patient_user'),
        ),
        migrations.AddConstraint(
            model_name='medicationlog',
            constraint=models.UniqueConstraint(fields=('medication', 'scheduled_time'), name='unique_medication_scheduled_log'),
        ),
        migrations.AddConstraint(
            model_name='sleepdevicesyncrecord',
            constraint=models.UniqueConstraint(fields=('patient_profile', 'provider', 'external_record_id'), name='unique_patient_device_sleep_record'),
        ),
        migrations.AddConstraint(
            model_name='sleepentry',
            constraint=models.UniqueConstraint(fields=('patient_profile', 'reference_date', 'provenance'), name='unique_sleep_entry_per_patient_date_provenance'),
        ),
    ]
