# Generated by Django 6.1 on 2026-09-04 10:55

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careplan",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="careplanaction",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="careplanpatientresponse",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-responded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="habit",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="habitcheckin",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-checked_in_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="habitoccurrence",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="medicationconsentshare",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="medicationlog",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-scheduled_time"],
            },
        ),
        migrations.AlterModelOptions(
            name="prescribedmedication",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-start_date", "medication_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="routineblock",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="sleepdevicesyncrecord",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-synced_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="sleepentry",
            options={
                "base_manager_name": "infrastructure_objects",
                "ordering": ["-reference_date"],
            },
        ),
        migrations.AlterModelManagers(
            name="careplan",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="careplanaction",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="careplanpatientresponse",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="habit",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="habitcheckin",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="habitoccurrence",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="medicationconsentshare",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="medicationlog",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="prescribedmedication",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="routineblock",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sleepdevicesyncrecord",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sleepentry",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
