# Generated by Django 6.1 on 2026-09-01 05:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0007_tighten_canonical_clinic_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_id", models.UUIDField(db_index=True)),
                ("requested_by_id", models.UUIDField()),
                ("assigned_to_id", models.UUIDField(blank=True, null=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Acesso"),
                            ("correction", "Correção"),
                            ("portability", "Portabilidade"),
                            ("revocation", "Revogação"),
                            ("erasure", "Eliminação"),
                        ],
                        max_length=24,
                    ),
                ),
                ("channel", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identity_pending", "Identidade pendente"),
                            ("in_review", "Em análise"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("processing", "Em execução"),
                            ("completed", "Concluída"),
                        ],
                        default="identity_pending",
                        max_length=24,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("identity_verified_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_evidence_digest",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_subject_requests",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExportArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encrypted_payload", models.BinaryField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("ciphertext_digest", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_artifact",
                        to="privacy.datasubjectrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReauthenticationProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_id", models.UUIDField(db_index=True)),
                ("method", models.CharField(default="password", max_length=32)),
                ("verified_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reauthentication_proofs",
                        to="clinics.clinic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destination_key", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmada"),
                            ("retained", "Retida"),
                            ("failed", "Falhou"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confirmation_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("retained_reason", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_destinations",
                        to="privacy.datasubjectrequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reauthenticationproof",
            index=models.Index(
                fields=["clinic", "actor_id", "expires_at"],
                name="privacy_reauth_actor_exp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasubjectrequest",
            index=models.Index(
                fields=["clinic", "status", "due_at"],
                name="privacy_dat_clinic__47e4aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasubjectrequest",
            index=models.Index(
                fields=["clinic", "subject_id", "requested_at"],
                name="privacy_dat_clinic__f88fe0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingdestination",
            constraint=models.UniqueConstraint(
                fields=("request", "destination_key"),
                name="privacy_unique_request_destination",
            ),
        ),
    ]
