# Generated by Django 6.1 on 2026-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasubjectrequest",
            name="identity_evidence_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="identity_verification_method",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="identity_verified_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datasubjectrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Confirmação"),
                    ("access", "Acesso"),
                    ("correction", "Correção"),
                    ("portability", "Portabilidade"),
                    ("revocation", "Revogação"),
                    ("erasure", "Eliminação"),
                ],
                max_length=24,
            ),
        ),
    ]
