# Generated by Django 6.1 on 2026-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0002_datasubjectrequest_identity_evidence_digest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingdestination",
            name="adapter_identity",
            field=models.CharField(default="legacy.unrecorded", max_length=128),
        ),
        migrations.AddField(
            model_name="processingdestination",
            name="adapter_version",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
