# Generated by Django 6.1 on 2026-09-02 14:11

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('people', '0003_carerelationship_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('horizon', models.CharField(choices=[('short', 'Curto prazo'), ('medium', 'Médio prazo'), ('long', 'Longo prazo')], default='short', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('archived', 'Arquivada')], default='active', max_length=16)),
                ('visibility', models.CharField(choices=[('shareable', 'Verde'), ('confirmation_required', 'Amarelo'), ('private', 'Vermelho')], default='private', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_created', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='clinics.clinic')),
                ('defining_actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_defined', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='people.patientprofile')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('created', 'Criada'), ('updated', 'Atualizada'), ('due_date_changed', 'Prazo alterado'), ('reopened', 'Reaberta'), ('completed', 'Concluída'), ('paused', 'Pausada'), ('resumed', 'Retomada'), ('archived', 'Arquivada'), ('step_done', 'Etapa concluída'), ('step_undone', 'Etapa reaberta')], max_length=32)),
                ('actor_id', models.UUIDField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_events', to='clinics.clinic')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='goals.goal')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('done_by_id', models.UUIDField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_steps', to='clinics.clinic')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='goals.goal')),
            ],
            options={
                'ordering': ('goal', 'order', 'id'),
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['clinic', 'patient_profile', 'status'], name='goal_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['clinic', 'visibility'], name='goal_clinic_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['clinic', 'goal', 'created_at'], name='goal_event_clinic_idx'),
        ),
        migrations.AddIndex(
            model_name='goalstep',
            index=models.Index(fields=['clinic', 'goal', 'is_done'], name='goal_step_clinic_done_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalstep',
            constraint=models.UniqueConstraint(fields=('goal', 'order'), name='unique_step_order_per_goal'),
        ),
    ]
