# Generated by Django 6.1 on 2026-09-02 14:41

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('goals', '0001_initial'),
        ('people', '0003_carerelationship_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowEnergyActionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('action_1', models.CharField(blank=True, max_length=255)),
                ('action_2', models.CharField(blank=True, max_length=255)),
                ('action_3', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='low_energy_action_templates', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_energy_action_templates', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_energy_action_templates', to='people.patientprofile')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'patient_profile', 'is_active'], name='lowenergy_tpl_patient_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'patient_profile', 'version'), name='unique_lowenergy_template_version_per_patient')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LowEnergyMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_1', models.CharField(blank=True, max_length=255)),
                ('action_2', models.CharField(blank=True, max_length=255)),
                ('action_3', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('suppress_non_essential_notifications', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='low_energy_sessions', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_energy_sessions', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_energy_sessions', to='people.patientprofile')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'patient_profile', 'started_at'], name='lowenergy_patient_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
