# Generated by Django 6.1 on 2026-09-02 15:14

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('goals', '0002_lowenergyactiontemplate_lowenergymode'),
        ('people', '0003_carerelationship_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(default='Pontual', max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by_patient', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Atribuído'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='assigned', max_length=32)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_exercises', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_assignments', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_assignments', to='people.patientprofile')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('last_step_completed', models.PositiveSmallIntegerField(default=0)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('shareable', 'Verde (compartilhado)'), ('confirmation_required', 'Amarelo (perguntar antes)'), ('private', 'Vermelho (somente eu)')], default='private', max_length=32)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='goals.exerciseassignment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_executions', to='clinics.clinic')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_executions', to='people.patientprofile')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_comments', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_comments', to='clinics.clinic')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goals.exerciseexecution')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('approach', models.CharField(default='Geral', max_length=64)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
                ('response_format', models.CharField(choices=[('text', 'Texto livre'), ('scale_1_5', 'Escala de 1 a 5'), ('single_choice', 'Escolha única'), ('multiple_choice', 'Múltipla escolha')], default='text', max_length=32)),
                ('accessibility_notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_exercises', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapeutic_exercises', to='clinics.clinic')),
                ('parent_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='goals.therapeuticexercise')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='exerciseassignment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='goals.therapeuticexercise'),
        ),
        migrations.AddIndex(
            model_name='exerciseexecution',
            index=models.Index(fields=['clinic', 'patient_profile', 'visibility'], name='execution_patient_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisecomment',
            index=models.Index(fields=['clinic', 'execution'], name='comment_clinic_execution_idx'),
        ),
        migrations.AddIndex(
            model_name='therapeuticexercise',
            index=models.Index(fields=['clinic', 'status'], name='exercise_clinic_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseassignment',
            index=models.Index(fields=['clinic', 'patient_profile', 'status'], name='assignment_patient_status_idx'),
        ),
    ]
