# Generated by Django 6.1 on 2026-09-02 17:11

import analytics.models
import analytics.storage
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('operational', 'Operacional')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('formulas', models.JSONField(blank=True, default=list)),
                ('limitations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Pronto'), ('failed', 'Falhou')], default='ready', max_length=16)),
                ('file', models.FileField(blank=True, max_length=255, storage=analytics.storage.PrivateReportStorage(), upload_to=analytics.models.report_file_upload_to)),
                ('download_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clinics.clinic')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'kind', 'created_at'], name='report_clinic_kind_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
