# Generated by Django 6.1 on 2026-09-02 18:27

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('scheduling', '0002_alter_messageattachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], default='open', max_length=16)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_justification', models.CharField(blank=True, max_length=255)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='scheduling.appointment')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_charges', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='clinics.clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='scheduling.service')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status', 'due_date'], name='charge_clinic_status_due_idx'), models.Index(fields=['clinic', 'appointment'], name='charge_clinic_appointment_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_charge_idempotency_per_clinic'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='charge_amount_non_negative'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='charge_discount_non_negative')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='clinics.clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='scheduling.service')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'service', 'valid_from'], name='price_clinic_service_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='service_price_non_negative'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='service_price_valid_dates')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
