# Generated by Django 6.1 on 2026-09-02 19:02

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('retired', 'Descontinuado')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('interval', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=16)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_prices', to='clinics.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='finance.plan')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Em teste'), ('active', 'Ativa'), ('past_due', 'Inadimplente'), ('paused', 'Pausada'), ('canceled', 'Cancelada')], default='trialing', max_length=16)),
                ('provider_token', models.CharField(blank=True, max_length=255)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clinics.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='finance.plan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Fixo')], max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('clinic', 'code'), name='unique_coupon_code_per_clinic'), models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='coupon_value_non_negative')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['clinic', 'code'], name='plan_clinic_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('clinic', 'code', 'version'), name='unique_plan_code_version_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='planprice',
            index=models.Index(fields=['clinic', 'plan', 'valid_from'], name='plan_price_idx'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='plan_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='plan_price_tax_non_negative'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['clinic', 'subscriber', 'status'], name='subscription_subscriber_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_subscription_idempotency_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_end__gte', models.F('current_period_start'))), name='subscription_period_valid'),
        ),
    ]
