# Generated by Django 6.1 on 2026-09-02 19:11

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('finance', '0002_plan_planprice_subscription_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=64)),
                ('provider_token', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('processed', 'Processado'), ('failed', 'Falhou'), ('duplicate', 'Duplicado')], default='received', max_length=16)),
                ('payload_digest', models.CharField(blank=True, max_length=64)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status', 'created_at'], name='webhook_clinic_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'external_event_id'), name='unique_webhook_event_per_clinic')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
