# Generated by Django 6.1 on 2026-09-02 19:24

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('finance', '0003_webhookevent'),
        ('scheduling', '0003_waitlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], default='open', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_hoc_charges', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_charges', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status', 'due_date'], name='adhoc_status_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_adhoc_idempotency_per_clinic'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='adhoc_amount_non_negative')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('orphan_charge', 'Cobrança órfã'), ('amount_mismatch', 'Divergência de valor'), ('invalid_webhook', 'Webhook inválido'), ('expired_dispute', 'Disputa vencida')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('resolved', 'Resolvido')], default='open', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_queue_items', to='clinics.clinic')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exception_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'kind', 'status'], name='exception_kind_status_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('full', 'Total'), ('partial', 'Parcial'), ('chargeback', 'Disputa')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justification', models.TextField(max_length=1000)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.charge')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='clinics.clinic')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status', 'created_at'], name='refund_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_refund_idempotency_per_clinic'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
