# Generated by Django 6.1 on 2026-09-02 19:31

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('finance', '0004_adhoccharge_exceptionqueueitem_refundrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('cash', 'Caixa'), ('receivable', 'Contas a receber'), ('revenue', 'Receita'), ('refund', 'Reembolso'), ('fee', 'Taxa'), ('payout', 'Repasse'), ('adjustment', 'Ajuste')], max_length=16)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_kind', models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('sequence', models.PositiveBigIntegerField()),
                ('entry_hash', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.ledgeraccount')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('closed_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('is_reopened', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_closures', to='clinics.clinic')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_closures_made', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_closures_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_source_type', models.CharField(max_length=64)),
                ('internal_source_id', models.CharField(max_length=64)),
                ('external_transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('matched', 'Conciliado'), ('divergent', 'Divergente')], default='pending', max_length=16)),
                ('internal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('tolerance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='clinics.clinic')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('cursor', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('external_transaction_count', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to='clinics.clinic')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('clinic', 'code'), name='unique_account_code_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['clinic', 'source_type', 'source_id'], name='ledger_source_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['clinic', 'account', 'created_at'], name='ledger_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('clinic', 'sequence'), name='unique_ledger_sequence_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='periodclosure',
            index=models.Index(fields=['clinic', 'period_start', 'period_end'], name='closure_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodclosure',
            constraint=models.UniqueConstraint(fields=('clinic', 'period_start', 'period_end'), name='unique_period_closure_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='periodclosure',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='closure_period_valid'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['clinic', 'status'], name='reconciliation_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.UniqueConstraint(fields=('clinic', 'external_transaction_id'), name='unique_reconciliation_external_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='statementimport',
            index=models.Index(fields=['clinic', 'provider', 'created_at'], name='statement_idx'),
        ),
    ]
