# Generated by Django 6.1 on 2026-09-02 19:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        ('finance', '0005_ledgeraccount_ledgerentry_periodclosure_and_more'),
        ('scheduling', '0003_waitlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Nota fiscal'), ('receipt', 'Recibo')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('issued', 'Emitido'), ('canceled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('document_number', models.CharField(blank=True, max_length=64)),
                ('competence_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('normalized_error', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='finance.charge')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_documents', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status', 'competence_date'], name='fiscal_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_fiscal_idempotency_per_clinic')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('settled', 'Liquidado'), ('failed', 'Falhou')], default='draft', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('calculation_memory', models.JSONField(blank=True, default=list)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_batches_approved', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='clinics.clinic')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'professional', 'status'], name='payout_batch_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_payout_batch_idempotency_per_clinic'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='payout_total_non_negative')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('percent_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('retention_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_rules', to='clinics.clinic')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_rules', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_rules', to='scheduling.service')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'professional', 'valid_from'], name='payout_rule_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('percent_rate__gte', 0), ('percent_rate__lte', 1)), name='payout_rate_between_zero_and_one'), models.CheckConstraint(condition=models.Q(('fixed_amount__gte', 0)), name='payout_fixed_non_negative'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='payout_rule_valid_dates')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
