# Generated by Django 6.1 on 2026-08-31 11:54

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["is_active", "slug"],
                        name="clinics_cli_is_acti_e8df2f_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClinicMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["clinic", "user", "is_active"],
                        name="clinics_cli_clinic__43b1d5_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active", "valid_from", "valid_until"],
                        name="clinics_cli_user_id_2880f4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "clinic"), name="unique_user_clinic_membership"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="membership_valid_until_on_or_after_start",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
