# Generated by Django 6.1 on 2026-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("clinics", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
