# Generated by Django 6.1 on 2026-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("clinics", "0002_add_clinic_is_demo")]

    operations = [
        migrations.RenameIndex(
            model_name="clinic",
            new_name="clinic_active_slug_idx",
            old_name="clinics_cli_is_acti_e8df2f_idx",
        ),
        migrations.RenameIndex(
            model_name="clinicmembership",
            new_name="membership_clinic_user_idx",
            old_name="clinics_cli_clinic__43b1d5_idx",
        ),
        migrations.RenameIndex(
            model_name="clinicmembership",
            new_name="membership_user_validity_idx",
            old_name="clinics_cli_user_id_2880f4_idx",
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["is_demo"], name="clinic_demo_idx"),
        ),
    ]
