# Generated by Django 6.1 on 2026-08-31 14:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("clinics", "0003_name_persistence_indexes")]

    operations = [
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="unique_clinic_slug_case_insensitive",
            ),
        ),
    ]
