# Generated by Django 6.1 on 2026-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("clinics", "0004_add_clinic_slug_invariant")]

    operations = [
        migrations.AlterField(
            model_name="clinicmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("clinic_admin", "Administrador da clínica"),
                    ("therapist", "Terapeuta"),
                    ("patient", "Paciente"),
                ],
                max_length=64,
            ),
        ),
    ]
