# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("clinics", "0005_document_membership_roles")]

    operations = [
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug__regex", r"^[a-z0-9]+(?:-[a-z0-9]+)*$")),
                name="clinic_slug_canonical_ascii_lowercase",
            ),
        ),
    ]
