# Generated by Django 6.1 on 2026-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0006_require_canonical_clinic_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clinic",
            name="clinic_slug_canonical_ascii_lowercase",
        ),
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug__regex", "^[a-z0-9]+(?:-[a-z0-9]+)*\\Z")),
                name="clinic_slug_canonical_ascii_lowercase",
            ),
        ),
    ]
