# Generated by Django 6.1 on 2026-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0007_tighten_canonical_clinic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("clinic_admin", "Administrador da clínica"),
                    ("therapist", "Terapeuta"),
                    ("administrative_staff", "Equipe administrativa"),
                    ("patient", "Paciente"),
                ],
                max_length=64,
            ),
        ),
    ]
