# Generated by Django 6.1 on 2026-09-02 07:15

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0008_alter_clinicmembership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "registration_identifier",
                    models.CharField(blank=True, max_length=64),
                ),
                ("administrative_email", models.EmailField(max_length=254)),
                ("administrative_phone", models.CharField(blank=True, max_length=32)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                ("postal_code", models.CharField(max_length=32)),
                ("country_code", models.CharField(max_length=2)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
