# Generated by Django 6.1 on 2026-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0009_clinicconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicconfiguration",
            name="language_code",
            field=models.CharField(default="pt-BR", max_length=10),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="out_of_hours_instructions",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="service_channels",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="timezone_name",
            field=models.CharField(default="America/Sao_Paulo", max_length=64),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="weekly_hours",
            field=models.JSONField(default=dict),
        ),
    ]
