# Generated by Django 6.1 on 2026-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0010_clinicconfiguration_language_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicconfiguration",
            name="service_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="clinicconfiguration",
            name="weekly_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
