# Generated by Django 6.1 on 2026-09-02 07:32

from django.db import migrations, models

import clinics.models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0011_alter_clinicconfiguration_service_channels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicconfiguration",
            name="logo",
            field=models.FileField(
                blank=True, upload_to=clinics.models.clinic_logo_upload_to
            ),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="primary_color",
            field=models.CharField(default="#1D4ED8", max_length=7),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="secondary_color",
            field=models.CharField(default="#93C5FD", max_length=7),
        ),
    ]
