# Generated by Django 6.1 on 2026-09-02 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0012_clinicconfiguration_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicconfiguration",
            name="enabled_modules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="modules_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="modules_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_module_configuration_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
