# Generated by Django 6.1 on 2026-09-02 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0013_clinicconfiguration_enabled_modules_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicmembership",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorized_clinic_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicmembership",
            name="unit_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="clinicmembership",
            index=models.Index(
                fields=["clinic", "role", "is_active", "valid_from", "valid_until"],
                name="membership_prof_list_idx",
            ),
        ),
    ]
