# Generated by Django 6.1 on 2026-09-03 00:25

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandThemeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('tokens', models.JSONField(default=dict)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_versions', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_theme_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'version'], name='brand_theme_ver_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'version'), name='unique_brand_theme_version_per_clinic')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('notification', 'Notificação'), ('public_page', 'Página Pública')], max_length=16)),
                ('purpose', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(max_length=20000)),
                ('allowed_variables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em Revisão'), ('active', 'Ativo'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_templates_approved', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comm_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('channel', 'purpose', '-version'),
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'channel', 'purpose', 'status'], name='comm_template_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'channel', 'purpose', 'version'), name='unique_template_version_per_clinic')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('verified', 'Verificado'), ('active', 'Ativo'), ('failed', 'Falhou'), ('revoked', 'Revogado')], default='pending', max_length=16)),
                ('verification_token', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tls_status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('renewal_due', 'Renovação Pendente'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('tls_provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('tls_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_domains_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'status'], name='custom_domain_status_idx'), models.Index(fields=['domain'], name='custom_domain_lookup_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
