# Generated by Django 6.1 on 2026-09-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_brandthemeversion_communicationtemplate_customdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconfiguration',
            name='icon',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='clinicconfiguration',
            name='institutional_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinicconfiguration',
            name='legal_text',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='clinicconfiguration',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clinicconfiguration',
            name='sender_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clinicconfiguration',
            name='typography',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
