# Generated by Django 6.1 on 2026-08-31 21:28

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_layout",
            field=models.CharField(
                choices=[("vertical", "Vertical"), ("detached", "Destacado")],
                default=accounts.models.default_workspace_layout,
                max_length=16,
            ),
        ),
    ]
