# Generated by Django 6.1 on 2026-09-01 07:11

from typing import Any

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models

import accounts.models


def canonicalize_existing_emails(apps: Any, schema_editor: Any) -> None:
    """Normalize existing identifiers and stop before any ambiguous merge."""
    del schema_editor
    user_model = apps.get_model("accounts", "User")
    seen: dict[str, Any] = {}
    updates: list[Any] = []
    for user in user_model.objects.all().only("id", "email"):
        canonical = user.email.strip().casefold()
        if not canonical:
            raise RuntimeError(f"User {user.id} has no e-mail identifier.")
        if canonical in seen:
            raise RuntimeError(
                "Case-insensitive duplicate e-mail identifiers exist for users "
                f"{seen[canonical]} and {user.id}."
            )
        seen[canonical] = user.id
        if canonical != user.email:
            user.email = canonical
            updates.append(user)
    if updates:
        user_model.objects.bulk_update(updates, ("email",))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_preferred_layout"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="credentials_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="security_state_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(
            canonicalize_existing_emails,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_user_email_case_insensitive",
            ),
        ),
    ]
