# Generated by Django 6.1 on 2026-09-01 08:48

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_email_identity_security"),
        ("clinics", "0007_tighten_canonical_clinic_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "initial_role",
                    models.CharField(
                        choices=[
                            ("clinic_admin", "Administrador da clínica"),
                            ("therapist", "Terapeuta"),
                            ("patient", "Paciente"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_clinic_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_clinic_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["clinic", "recipient_email", "expires_at"],
                        name="invite_clinic_email_exp_idx",
                    ),
                    models.Index(
                        fields=["clinic", "used_at", "revoked_at"],
                        name="invite_clinic_state_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("used_at__isnull", True),
                            ("revoked_at__isnull", True),
                            _connector="OR",
                        ),
                        name="invitation_not_used_and_revoked",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
