# Generated by Django 6.1 on 2026-09-04 09:22

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiEvaluationBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('dataset_version', models.CharField(max_length=32)),
                ('cases_json', models.JSONField(default=list)),
                ('target_metrics', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AiAssistantRolloutFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('emergency_kill_switch', models.BooleanField(default=False)),
                ('max_context_chars', models.PositiveIntegerField(default=4000)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rollout_flag', to='clinics.clinic')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AiGuardrailViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_category', models.CharField(choices=[('diagnosis', 'DIAGNOSIS'), ('prescription', 'PRESCRIPTION'), ('test_interpretation', 'TEST_INTERPRETATION'), ('autonomous_triage', 'AUTONOMOUS_TRIAGE'), ('risk_score', 'RISK_SCORE'), ('treatment_decision', 'TREATMENT_DECISION'), ('unvalidated_alert', 'UNVALIDATED_ALERT'), ('disciplinary_or_insurance', 'DISCIPLINARY_OR_INSURANCE'), ('adversarial_jailbreak', 'ADVERSARIAL_JAILBREAK')], max_length=48)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('explanation_provided', models.TextField()),
                ('triggered_rules', models.JSONField(default=list)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_guardrail_violations', to='clinics.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_guardrail_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AiModelInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=128)),
                ('processing_region', models.CharField(default='sa-east-1', max_length=64)),
                ('legal_basis', models.CharField(default='Legítimo Interesse / Execução de Contrato', max_length=128)),
                ('risk_tier', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('prohibited', 'PROHIBITED')], default='low', max_length=32)),
                ('reevaluation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_ai_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'unique_together': {('name', 'version')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AiEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fidelity_score', models.FloatField()),
                ('omission_score', models.FloatField()),
                ('refusal_accuracy', models.FloatField()),
                ('bias_score', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_assistant.aievaluationbenchmark')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('model_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='ai_assistant.aimodelinventory')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AiDraftingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('task_type', models.CharField(choices=[('clinical_synthesis', 'CLINICAL_SYNTHESIS'), ('text_formatting', 'TEXT_FORMATTING'), ('observation_summarization', 'OBSERVATION_SUMMARIZATION')], default='clinical_synthesis', max_length=48)),
                ('input_text_hash', models.CharField(max_length=64)),
                ('source_snippets', models.JSONField(default=list)),
                ('generated_draft', models.TextField()),
                ('uncertainty_notes', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('draft', 'DRAFT'), ('accepted', 'ACCEPTED'), ('edited', 'EDITED'), ('rejected', 'REJECTED')], default='draft', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_content', models.TextField(blank=True)),
                ('prompt_version', models.CharField(default='1.0.0', max_length=32)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_drafting_sessions', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafting_sessions', to='clinics.clinic')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_drafts', to=settings.AUTH_USER_MODEL)),
                ('model_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafting_sessions', to='ai_assistant.aimodelinventory')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
