# Generated by Django 6.1 on 2026-09-01 19:31

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0008_alter_clinicmembership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms", "Termos de uso"),
                            ("privacy_notice", "Aviso de privacidade"),
                            ("clinical_limits", "Ciência de limites"),
                            ("consent", "Consentimento"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("purpose", models.CharField(max_length=100)),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Todos"),
                            ("patient", "Pacientes"),
                            ("professional", "Profissionais"),
                            ("administrative", "Equipe administrativa"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("refusal_consequence", models.TextField()),
                ("alternative_instructions", models.TextField()),
                ("clinic_contact_instructions", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("publication_hash", models.CharField(blank=True, max_length=64)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_documents",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_consent_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConsentManifestation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("accepted", "Aceitou"), ("refused", "Recusou")],
                        max_length=16,
                    ),
                ),
                ("purpose", models.CharField(max_length=100)),
                ("document_hash", models.CharField(max_length=64)),
                ("evidence_digest", models.CharField(max_length=64)),
                (
                    "representation_evidence_digest",
                    models.CharField(blank=True, max_length=64),
                ),
                ("manifested_at", models.DateTimeField()),
                ("sequence", models.PositiveIntegerField()),
                ("request_id", models.UUIDField()),
                ("source", models.CharField(default="web", max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_manifestations",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifestations",
                        to="consents.consentdocument",
                    ),
                ),
                (
                    "represented_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="represented_consent_manifestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_manifestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="consentdocument",
            index=models.Index(
                fields=["clinic", "audience", "is_active", "effective_from"],
                name="consent_doc_current_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentdocument",
            constraint=models.UniqueConstraint(
                fields=("clinic", "document_type", "purpose", "audience", "version"),
                name="consent_unique_document_version",
            ),
        ),
        migrations.AddIndex(
            model_name="consentmanifestation",
            index=models.Index(
                fields=["clinic", "subject", "purpose", "manifested_at"],
                name="consent_subject_purpose_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentmanifestation",
            constraint=models.UniqueConstraint(
                fields=("clinic", "request_id"),
                name="consent_unique_manifestation_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentmanifestation",
            constraint=models.UniqueConstraint(
                fields=("clinic", "document", "subject", "sequence"),
                name="consent_unique_subject_sequence",
            ),
        ),
    ]
