# Generated by Django 6.1 on 2026-09-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentmanifestation",
            name="revocation_reason_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="consentmanifestation",
            name="decision",
            field=models.CharField(
                choices=[
                    ("accepted", "Aceitou"),
                    ("refused", "Recusou"),
                    ("revoked", "Revogou"),
                ],
                max_length=16,
            ),
        ),
    ]
