# Generated by Django 6.1 on 2026-09-01 21:53

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0008_alter_clinicmembership_role"),
        ("consents", "0002_consentmanifestation_revocation_reason_digest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRevocationDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destination", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_digest", models.CharField(blank=True, max_length=64)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_revocation_dispatches",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "manifestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revocation_dispatches",
                        to="consents.consentmanifestation",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["clinic", "status", "created_at"],
                        name="consent_revocation_queue_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "manifestation", "destination"),
                        name="consent_unique_revocation_destination",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
