# Generated by Django 6.1 on 2026-09-01 22:05

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0008_alter_clinicmembership_role"),
        ("consents", "0003_consentrevocationdispatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalRepresentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("legal_guardian", "Responsável legal"),
                            ("court_guardian", "Curador judicial"),
                            ("authorized_representative", "Procurador"),
                        ],
                        max_length=32,
                    ),
                ),
                ("granted_purposes", models.JSONField(default=list)),
                ("evidence_digest", models.CharField(max_length=64)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verificada"),
                            ("suspended", "Suspensa"),
                            ("expired", "Expirada"),
                            ("revoked", "Revogada"),
                        ],
                        default="verified",
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("next_review_at", models.DateField()),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_representations",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_representations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "represented_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_representations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_representations_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=[
                            "clinic",
                            "representative",
                            "represented_subject",
                            "status",
                        ],
                        name="consent_repr_access_idx",
                    ),
                    models.Index(
                        fields=["clinic", "status", "next_review_at"],
                        name="consent_repr_review_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("representative", models.F("represented_subject")),
                            _negated=True,
                        ),
                        name="consent_representation_distinct_people",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__gte", models.F("valid_from"))
                        ),
                        name="consent_representation_valid_dates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("next_review_at__lte", models.F("valid_until"))
                        ),
                        name="consent_representation_review_within_validity",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
