# Generated by Django 6.1 on 2026-09-01 22:39

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0008_alter_clinicmembership_role"),
        ("consents", "0005_consentrevocationdispatch_adapter_identity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessReviewRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_date", models.DateField()),
                ("reviewed_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_access_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_review_runs",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AccessReviewException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.UUIDField()),
                ("reason", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberta"), ("resolved", "Resolvida")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_digest", models.CharField(blank=True, max_length=64)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_review_exceptions",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_access_review_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="first_seen_exceptions",
                        to="consents.accessreviewrun",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_seen_exceptions",
                        to="consents.accessreviewrun",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRevocationDispatchAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[("confirmed", "Confirmado"), ("failed", "Falhou")],
                        max_length=16,
                    ),
                ),
                ("adapter_identity", models.CharField(max_length=100)),
                ("adapter_version", models.CharField(max_length=32)),
                ("evidence_digest", models.CharField(max_length=64)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_revocation_dispatch_attempts",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="consents.consentrevocationdispatch",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="accessreviewrun",
            index=models.Index(
                fields=["clinic", "-review_date"], name="consent_access_review_run_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessreviewrun",
            constraint=models.UniqueConstraint(
                fields=("clinic", "review_date"),
                name="consent_unique_access_review_date",
            ),
        ),
        migrations.AddIndex(
            model_name="accessreviewexception",
            index=models.Index(
                fields=["clinic", "status", "created_at"],
                name="consent_access_exception_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessreviewexception",
            constraint=models.UniqueConstraint(
                fields=("clinic", "resource_type", "resource_id", "reason"),
                name="consent_unique_access_exception",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrevocationdispatchattempt",
            index=models.Index(
                fields=["clinic", "dispatch", "attempt_number"],
                name="consent_dispatch_attempt_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrevocationdispatchattempt",
            constraint=models.UniqueConstraint(
                fields=("dispatch", "attempt_number"),
                name="consent_unique_dispatch_attempt",
            ),
        ),
    ]
