# Generated by Django 6.1 on 2026-09-01 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0007_consentrevocationworkitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="consentrevocationworkitem",
            name="consent_work_item_queue_idx",
        ),
        migrations.AddIndex(
            model_name="consentrevocationworkitem",
            index=models.Index(
                fields=["status", "created_at"], name="consent_work_item_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrevocationworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("acknowledged_at__isnull", True),
                        ("acknowledged_by__isnull", True),
                        ("acknowledgement_digest", ""),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("acknowledged_at__isnull", False),
                        ("acknowledged_by__isnull", False),
                        ("status", "acknowledged"),
                        models.Q(("acknowledgement_digest", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="consent_work_item_ack_evidence_ck",
            ),
        ),
        migrations.RemoveField(
            model_name="consentrevocationworkitem",
            name="clinic",
        ),
    ]
