# Generated by Django 6.1 on 2026-09-01 04:48

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0007_tighten_canonical_clinic_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("clinic_switch", "Troca de clínica"),
                            ("view", "Visualização"),
                            ("create", "Criação"),
                            ("update", "Alteração"),
                            ("export", "Exportação"),
                            ("consent_accept", "Aceite de consentimento"),
                            ("consent_revoke", "Revogação de consentimento"),
                            ("permission_change", "Alteração de permissão"),
                            ("delete", "Exclusão"),
                            ("audit_query", "Consulta de auditoria"),
                        ],
                        max_length=32,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("denied", "Negado"),
                            ("error", "Erro"),
                        ],
                        max_length=16,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("network_origin_digest", models.CharField(blank=True, max_length=64)),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                ("event_hash", models.CharField(max_length=64, unique=True)),
                ("retention_until", models.DateTimeField()),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["clinic", "occurred_at"], name="audit_clinic_time_idx"
                    ),
                    models.Index(
                        fields=["clinic", "actor_id", "occurred_at"],
                        name="audit_clinic_actor_idx",
                    ),
                    models.Index(
                        fields=["clinic", "action", "outcome"],
                        name="audit_clinic_action_idx",
                    ),
                    models.Index(
                        fields=["clinic", "resource_type", "resource_id"],
                        name="audit_clinic_resource_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "sequence"),
                        name="unique_audit_sequence_per_clinic",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
