# Generated by Django 6.1 on 2026-09-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("clinics", "0007_tighten_canonical_clinic_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditCheckpoint",
            fields=[
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="audit_checkpoint",
                        serialize=False,
                        to="clinics.clinic",
                    ),
                ),
                ("terminal_sequence", models.PositiveBigIntegerField()),
                ("terminal_hash", models.CharField(max_length=64)),
                ("signature", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
