# Generated by Django 6.1 on 2026-09-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_auditcheckpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="justification_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
