# Generated by Django 6.1 on 2026-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_auditevent_justification_digest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("clinic_switch", "Troca de clínica"),
                    ("view", "Visualização"),
                    ("create", "Criação"),
                    ("update", "Alteração"),
                    ("export", "Exportação"),
                    ("consent_accept", "Aceite de consentimento"),
                    ("consent_refuse", "Recusa de consentimento"),
                    ("consent_revoke", "Revogação de consentimento"),
                    ("permission_change", "Alteração de permissão"),
                    ("delete", "Exclusão"),
                    ("audit_query", "Consulta de auditoria"),
                ],
                max_length=32,
            ),
        ),
    ]
