# Generated by Django 6.1 on 2026-09-03 21:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('scheduling', '0003_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='video_provider', max_length=64)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('join_url', models.URLField(max_length=500)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_recording_enabled', models.BooleanField(default=False)),
                ('fallback_url', models.URLField(blank=True, max_length=500)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_session', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_step', models.CharField(max_length=64)),
                ('status', models.CharField(default='started', max_length=32)),
                ('steps_completed', models.JSONField(blank=True, default=list)),
                ('compensation_log', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sagas', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_sagas', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status', '-created_at'], name='integration_clinic__91a444_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalCalendarMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('external_calendar_id', models.CharField(max_length=255)),
                ('external_event_id', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('sync_status', models.CharField(default='synced', max_length=32)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('conflict_details', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_mappings', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_mappings', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'provider'), name='unique_appointment_calendar_provider')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationAuditMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=128)),
                ('outcome', models.CharField(max_length=32)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_metrics', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'operation', 'outcome', '-created_at'], name='integration_provide_4d76f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('google_calendar', 'Google Calendar'), ('microsoft_outlook', 'Microsoft Outlook'), ('video_provider', 'Provedor de Vídeo')], max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('expired', 'Expirada'), ('revoked', 'Revogada')], default='pending', max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('encrypted_payload', models.BinaryField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_credentials', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'provider', 'name'), name='unique_credential_name_per_clinic_provider')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('google_calendar', 'Google Calendar'), ('microsoft_outlook', 'Microsoft Outlook'), ('video_provider', 'Provedor de Vídeo')], max_length=64)),
                ('external_event_id', models.CharField(max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sanitized_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado'), ('failed', 'Falha'), ('dead_letter', 'Dead Letter')], default='pending', max_length=32)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_webhook_events', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'status', '-received_at'], name='integration_provide_7a55c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='unique_webhook_provider_event')],
            },
        ),
    ]
