# Generated by Django 6.1 on 2026-09-03 21:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('integrations', '0001_initial'),
        ('scheduling', '0003_waitlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_phone', models.CharField(max_length=32)),
                ('external_message_id', models.CharField(max_length=255, unique=True)),
                ('correlation_token', models.CharField(blank=True, max_length=64)),
                ('raw_text', models.CharField(max_length=500)),
                ('action_parsed', models.CharField(choices=[('confirm', 'Confirmar'), ('reschedule', 'Remarcar'), ('cancel', 'Cancelar'), ('opt_out', 'Opt-out / Parar'), ('unknown', 'Não reconhecido')], default='unknown', max_length=32)),
                ('processed', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_replies', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_inbound_messages', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('purpose', models.CharField(default='appointment_reminders', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('revoked', 'Revogado')], default='active', max_length=32)),
                ('consent_version', models.CharField(default='1.0', max_length=32)),
                ('consent_text_snapshot', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_consents', to='clinics.clinic')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'phone_number', 'status'], name='integration_clinic__6a01fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'phone_number', 'purpose'), name='unique_whatsapp_consent_clinic_phone_purpose')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('template_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falha')], default='pending', max_length=32)),
                ('fallback_channel', models.CharField(blank=True, max_length=32)),
                ('error_details', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_timeline_messages', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status', '-created_at'], name='integration_clinic__abf320_idx'), models.Index(fields=['provider_message_id'], name='integration_provide_3316c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('language', models.CharField(default='pt_BR', max_length=16)),
                ('category', models.CharField(default='UTILITY', max_length=64)),
                ('body_template', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'name', 'language'), name='unique_whatsapp_template_clinic_name_lang')],
            },
        ),
    ]
