# Generated by Django 6.1 on 2026-09-03 21:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('integrations', '0002_whatsappinboundmessage_whatsappconsentrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('therapist', 'Terapeuta'), ('patient', 'Paciente')], max_length=32)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('device_check_completed', models.BooleanField(default=False)),
                ('in_waiting_room', models.BooleanField(default=False)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='integrations.videosession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoQualityTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packet_loss_percent', models.FloatField(default=0.0)),
                ('jitter_ms', models.FloatField(default=0.0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('degradation_detected', models.BooleanField(default=False)),
                ('contingency_activated', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_telemetry', to='clinics.clinic')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='integrations.videosession')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
