# Generated by Django 6.1 on 2026-09-04 09:45

import django.db.models.deletion
import django.utils.timezone
import integrations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_clinicconfiguration_icon_and_more'),
        ('integrations', '0003_videoaccesstoken_videoqualitytelemetry'),
        ('people', '0004_review_governance_wave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaccesstoken',
            name='role',
            field=models.CharField(choices=[('therapist', 'Terapeuta'), ('patient', 'Paciente'), ('observer', 'Observador')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoaccesstoken',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(default=integrations.models._default_client_id, max_length=64, unique=True)),
                ('client_name', models.CharField(max_length=128)),
                ('client_type', models.CharField(choices=[('confidential', 'Confidencial'), ('public_pkce', 'Público com PKCE')], default='confidential', max_length=32)),
                ('allowed_scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('revoked', 'Revogado')], default='active', max_length=32)),
                ('rate_limit_rpm', models.IntegerField(default=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('jti', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to='clinics.clinic')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='integrations.apiclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiClientSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_hash', models.CharField(max_length=128)),
                ('secret_hint', models.CharField(max_length=8)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='integrations.apiclient')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_client_secrets', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.IntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='integrations.apiclient')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_idempotency_records', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CsvExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=255)),
                ('encoding', models.CharField(default='utf-8-sig', max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Carregado'), ('previewed', 'Prévia Gerada'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falha')], default='processing', max_length=32)),
                ('row_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_export_jobs', to='clinics.clinic')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CsvImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(max_length=64)),
                ('template_version', models.CharField(default='1.0', max_length=16)),
                ('status', models.CharField(choices=[('uploaded', 'Carregado'), ('previewed', 'Prévia Gerada'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falha')], default='uploaded', max_length=32)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('rejected_rows', models.IntegerField(default=0)),
                ('quarantined_filename', models.CharField(blank=True, max_length=255)),
                ('rejection_report', models.JSONField(blank=True, default=list)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_import_jobs', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationRolloutFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_key', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('canary_percentage', models.IntegerField(default=0)),
                ('error_budget_percentage', models.FloatField(default=100.0)),
                ('rollback_triggered', models.BooleanField(default=False)),
                ('rollback_reason', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollout_flags', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=64)),
                ('idempotency_token', models.CharField(max_length=128)),
                ('base_version', models.IntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Na Fila'), ('synced', 'Sincronizado'), ('conflict', 'Conflito Detectado'), ('rejected', 'Rejeitado')], default='queued', max_length=32)),
                ('conflict_details', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sync_items', to='clinics.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sync_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSecurityAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_name', models.CharField(max_length=128)),
                ('dpa_signed', models.BooleanField(default=False)),
                ('data_residency', models.CharField(default='BR', max_length=16)),
                ('subprocessors', models.JSONField(blank=True, default=list)),
                ('sla_tier', models.CharField(default='standard', max_length=32)),
                ('exit_plan_documented', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('suspended', 'Suspenso'), ('terminated', 'Encerrado')], default='pending', max_length=32)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partner_agreements', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_security_agreements', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WearableConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('opt_in', models.BooleanField(default=True)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device_identifier', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_connections', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_connections', to='people.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WearableMetricSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('steps', 'Passos'), ('resting_heart_rate', 'Frequência Cardíaca de Repouso'), ('sleep_duration_minutes', 'Duração do Sono (min)'), ('active_minutes', 'Minutos Ativos')], max_length=64)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('recorded_at', models.DateTimeField()),
                ('provenance', models.CharField(max_length=128)),
                ('quality_score', models.FloatField(default=1.0)),
                ('is_informative_only', models.BooleanField(default=True, editable=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_metric_samples', to='clinics.clinic')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='integrations.wearableconnection')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_url', models.URLField(max_length=500)),
                ('secret_key', models.CharField(max_length=128)),
                ('rotated_secret_key', models.CharField(blank=True, max_length=128)),
                ('events_subscribed', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=5)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('signature_header', models.CharField(max_length=255)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('failed', 'Falha'), ('dead_letter', 'Dead Letter')], default='pending', max_length=32)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_attempts', to='clinics.clinic')),
                ('replay_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_webhook_replays', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='integrations.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['clinic', 'status', 'client_id'], name='integration_clinic__b22cea_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesstoken',
            index=models.Index(fields=['clinic', 'is_revoked', 'expires_at'], name='integration_clinic__976765_idx'),
        ),
        migrations.AddIndex(
            model_name='apiidempotencyrecord',
            index=models.Index(fields=['clinic', 'expires_at'], name='integration_clinic__a0d67b_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_clinic_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='integrationrolloutflag',
            constraint=models.UniqueConstraint(fields=('clinic', 'feature_key'), name='unique_clinic_integration_rollout_flag'),
        ),
        migrations.AddIndex(
            model_name='offlinesyncqueueitem',
            index=models.Index(fields=['clinic', 'device_id', 'status'], name='integration_clinic__f7aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='wearablemetricsample',
            index=models.Index(fields=['clinic', 'connection', 'metric_type', '-recorded_at'], name='integration_clinic__558c59_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['clinic', 'status', '-created_at'], name='integration_clinic__4f17ed_idx'),
        ),
    ]
