# Generated by Django 6.1 on 2026-09-02 08:55

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import people.models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0013_clinicconfiguration_enabled_modules_and_more"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("social_name", models.CharField(blank=True, max_length=255)),
                ("professional_email", models.EmailField(max_length=254)),
                ("professional_phone", models.CharField(blank=True, max_length=32)),
                (
                    "photo",
                    models.FileField(
                        blank=True, upload_to=people.models.professional_photo_upload_to
                    ),
                ),
                ("biography", models.TextField(blank=True, max_length=2000)),
                (
                    "accessibility_preferences",
                    models.TextField(blank=True, max_length=1000),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("psychologist", "Psicologia"),
                            ("therapist", "Terapia"),
                            ("other", "Outra categoria"),
                        ],
                        max_length=32,
                    ),
                ),
                ("specialties", models.JSONField(blank=True, default=list)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_profiles",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professional_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("council_name", models.CharField(blank=True, max_length=64)),
                ("council_number", models.CharField(blank=True, max_length=64)),
                ("council_jurisdiction", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("declared", "Informado pelo profissional")],
                        default="declared",
                        max_length=16,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="people.professionalprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(
                fields=["clinic", "category", "full_name"],
                name="prof_clinic_category_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="professionalprofile",
            constraint=models.UniqueConstraint(
                fields=("clinic", "user"), name="unique_professional_profile_per_clinic"
            ),
        ),
    ]
