# Generated by Django 6.1 on 2026-09-02 09:20

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_clinicinvitation_initial_role"),
        ("clinics", "0014_clinicmembership_authorized_by_and_more"),
        ("people", "0002_professionalprofile_professionalcredential_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carerelationship",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorized_care_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carerelationship",
            name="function",
            field=models.CharField(default="primary_therapist", max_length=64),
        ),
        migrations.AlterField(
            model_name="carerelationship",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_care_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("social_name", models.CharField(blank=True, max_length=255)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("woman", "Mulher"),
                            ("man", "Homem"),
                            ("non_binary", "Pessoa não binária"),
                            ("other", "Outro"),
                            ("undisclosed", "Prefiro não informar"),
                        ],
                        max_length=16,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("language_code", models.CharField(default="pt-BR", max_length=16)),
                (
                    "timezone_name",
                    models.CharField(default="America/Sao_Paulo", max_length=64),
                ),
                (
                    "accessibility_preferences",
                    models.TextField(blank=True, max_length=1000),
                ),
                ("address", models.JSONField(blank=True, default=dict)),
                ("address_purpose", models.CharField(blank=True, max_length=255)),
                ("emergency_contact", models.JSONField(blank=True, default=dict)),
                (
                    "emergency_contact_purpose",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profiles",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PatientInvitationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile_link",
                        to="accounts.clinicinvitation",
                    ),
                ),
                (
                    "patient_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_link",
                        to="people.patientprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carerelationship",
            name="patient_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_relationships",
                to="people.patientprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["clinic", "email"], name="patient_clinic_email_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["clinic", "phone"], name="patient_clinic_phone_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="patientprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("clinic", "user"),
                name="unique_linked_patient_account_per_clinic",
            ),
        ),
    ]
