# Generated by Django 6.1 on 2026-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_carerelationship_authorized_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalcredential',
            name='status',
            field=models.CharField(choices=[('declared', 'Informado pelo profissional'), ('verified', 'Verificado pela clínica'), ('revoked', 'Revogado')], default='declared', max_length=16),
        ),
    ]
