"""Settings for local development with PostgreSQL."""

import os

from .base import (  # noqa: F401
    ACCOUNT_SESSION_ABSOLUTE_SECONDS,
    ACCOUNT_SESSION_IDLE_SECONDS,
    ASGI_APPLICATION,
    AUDIT_RETENTION_DAYS,
    AUTH_PASSWORD_VALIDATORS,
    AUTH_USER_MODEL,
    BASE_DIR,
    CACHES,
    CONSENT_REVOCATION_DESTINATIONS,
    DEFAULT_AUTO_FIELD,
    DEFAULT_FROM_EMAIL,
    INSTALLED_APPS,
    LANGUAGE_CODE,
    LOCALE_PATHS,
    LOGGING,
    LOGIN_RATE_LIMIT_ATTEMPTS,
    LOGIN_RATE_LIMIT_WINDOW_SECONDS,
    LOGIN_URL,
    MAILERS,
    MEDIA_ROOT,
    MEDIA_URL,
    MFA_ENCRYPTION_KEY,
    MFA_ENFORCEMENT_ENABLED,
    MFA_RATE_LIMIT_ATTEMPTS,
    MFA_RATE_LIMIT_WINDOW_SECONDS,
    MIDDLEWARE,
    PASSWORD_RECOVERY_RATE_LIMIT_ATTEMPTS,
    PASSWORD_RECOVERY_RATE_LIMIT_WINDOW_SECONDS,
    PASSWORD_RESET_TIMEOUT,
    PRIVACY_EXPORT_TTL_SECONDS,
    PRIVACY_LIFECYCLE_DESTINATIONS,
    PRIVACY_REAUTH_MAX_AGE_SECONDS,
    PRIVACY_REQUEST_DUE_DAYS,
    PRIVATE_MEDIA_ROOT,
    PRIVATE_UPLOAD_MALWARE_SCAN_COMMAND,
    ROOT_URLCONF,
    STATIC_ROOT,
    STATIC_URL,
    STATICFILES_DIRS,
    TEMPLATES,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
    WSGI_APPLICATION,
    environment_flag,
    postgres_database_from_environment,
    required_environment,
)

SECRET_KEY = required_environment("DJANGO_SECRET_KEY")
AUDIT_INTEGRITY_KEY = required_environment("AUDIT_INTEGRITY_KEY")
DEBUG = True
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]"
    ).split(",")
    if host.strip()
]
DATABASES = {"default": postgres_database_from_environment()}
ALLOW_DEMO_SEED = environment_flag("DJANGO_ALLOW_DEMO_SEED")
