# Generated by Django 6.1 on 2026-09-02 11:51

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0014_clinicmembership_authorized_by_and_more"),
        ("people", "0003_carerelationship_authorized_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("contact_preferences", models.JSONField(blank=True, default=dict)),
                ("reminder_windows", models.JSONField(blank=True, default=dict)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("goals", "Objetivos"),
                            ("preferences", "Preferências"),
                            ("terms", "Termos e limites"),
                            ("complete", "Concluído"),
                        ],
                        default="goals",
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_onboardings",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="people.patientprofile",
                    ),
                ),
            ],
            options={
                "base_manager_name": "infrastructure_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["clinic", "current_step"],
                        name="onboarding_clinic_step_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("infrastructure_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
