# Generated by Django 6.1 on 2026-09-02 19:55

import content.models
import content.storage
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0014_clinicmembership_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('article', 'Artigo'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('exercise', 'Exercício')], max_length=16)),
                ('language_code', models.CharField(default='pt-BR', max_length=10)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('audience', models.CharField(choices=[('patient', 'Paciente'), ('professional', 'Profissional')], default='patient', max_length=16)),
                ('contraindications', models.TextField(blank=True, max_length=1000)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, storage=content.storage.PrivateContentStorage(), upload_to=content.models.content_media_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_media', to='clinics.clinic')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='content.content')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_media_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField(max_length=50000)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('archived', 'Arquivado')], max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('body_hash', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='clinics.clinic')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.content')),
            ],
            options={
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['clinic', 'kind', 'status'], name='content_kind_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('clinic', 'slug'), name='unique_content_slug_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='contentmedia',
            index=models.Index(fields=['clinic', 'content'], name='content_media_idx'),
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['clinic', 'status', 'scheduled_for'], name='content_version_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(fields=('content', 'version'), name='unique_version_per_content'),
        ),
    ]
