# Generated by Django 6.1 on 2026-09-03 09:18

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_brandthemeversion_communicationtemplate_customdomain'),
        ('content', '0005_content_recommendations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('quiz', 'user', 'request_id'), name='unique_quiz_attempt_request_per_user'),
        ),
    ]
