# Generated by Django 6.1 on 2026-09-03 09:30

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_brandthemeversion_communicationtemplate_customdomain'),
        ('content', '0006_quiz_attempt_request_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrecommendation',
            name='context',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='credential_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='credential_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='priority',
            field=models.CharField(default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='approver_credential_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='review_evidence',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='review_opinion',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='review_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='review_required_specialty',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='review_signed_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='review_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_kind', models.CharField(choices=[('recommendation_active', 'Recomendação atribuída'), ('recommendation_retired', 'Recomendação retirada'), ('content_removed', 'Conteúdo removido')], max_length=32)),
                ('body', models.CharField(max_length=500)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_%(class)ss', to='clinics.clinic')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_notifications', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='content.contentrecommendation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'infrastructure_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['clinic', 'recipient', 'created_at'], name='content_notification_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('infrastructure_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
