# Generated by Django 6.1 on 2026-09-03 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_brandthemeversion_communicationtemplate_customdomain'),
        ('content', '0010_contentversioncomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_active_enrollment_per_course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='end_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='option_order',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='shuffle_seed',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('course', 'user'), name='unique_active_enrollment_per_course'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_reason', ''), ('ended_at__isnull', True)), models.Q(('ended_at__isnull', False), models.Q(('end_reason', ''), _negated=True)), _connector='OR'), name='enrollment_end_state_coherent'),
        ),
    ]
