# Generated by Django 6.1 on 2026-09-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_enrollment_unique_active_enrollment_per_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='captions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
